function [rec_text, dominant_category] = recommendation_engine(scores, m_e, m_s, route)
% RECOMMENDATION_ENGINE  Generates a human-readable recommendation string.
%
%   Inputs:
%     scores  — output from scoring_framework.m
%     m_e     — eVTOL metrics from mission_sim.m
%     m_s     — eSTOL metrics from mission_sim.m
%     route   — route struct
%
%   Outputs:
%     rec_text          — recommendation string for App display
%     dominant_category — category that most influenced the result

% Find dominant category (largest score gap)
categories = {'energy','performance','aero','operational'};
gaps = zeros(1, length(categories));
for i = 1:length(categories)
    cat = categories{i};
    gaps(i) = abs(scores.evtol_category.(cat) - scores.estol_category.(cat));
end
[~, dom_idx]    = max(gaps);
dominant_category = categories{dom_idx};

winner  = scores.winner;
loser   = 'eSTOL'; if strcmp(winner, 'eSTOL'); loser = 'eVTOL'; end
margin  = scores.margin * 100;
dist_km = route.distance_m / 1e3;
offset  = route.estol_offset_m / 1e3;

% Energy gap
e_gap_pct = (m_e.energy_per_km - m_s.energy_per_km) / m_s.energy_per_km * 100;

% Build recommendation text
if strcmp(winner, 'Tie')
    rec_text = sprintf([...
        'For a %.0f km route, eVTOL and eSTOL are closely matched '...
        '(margin < 2%%). The choice depends on infrastructure availability. '...
        'If a %.1f km runway offset is acceptable, eSTOL offers similar '...
        'performance with %.1f%% better energy efficiency. '...
        'If landing flexibility is critical, eVTOL is preferred.'], ...
        dist_km, offset, abs(e_gap_pct));
    return
end

% Dominant category explanation
cat_explanations = struct(...
    'energy',      'energy efficiency', ...
    'performance', 'mission performance', ...
    'aero',        'aerodynamic efficiency', ...
    'operational', 'operational cost and route distance');

dom_label = cat_explanations.(dominant_category);

% Winner-specific text
if strcmp(winner, 'eVTOL')
    rec_text = sprintf([...
        '%s is recommended for this %.0f km route '...
        '(score: %.2f vs %.2f, margin: %.1f%%). '...
        'The deciding factor is %s. '...
        'eVTOL eliminates the %.1f km runway offset required by eSTOL, '...
        'which is significant at this route distance. '...
        'Note: eSTOL uses %.1f%% less energy per km, so '...
        'if the infrastructure is available, eSTOL may be preferable for '...
        'high-frequency operations.'], ...
        winner, dist_km, scores.evtol_total, scores.estol_total, margin, ...
        dom_label, offset, abs(e_gap_pct));
else
    rec_text = sprintf([...
        '%s is recommended for this %.0f km route '...
        '(score: %.2f vs %.2f, margin: %.1f%%). '...
        'The deciding factor is %s. '...
        'eSTOL uses %.1f%% less energy per km despite flying %.1f km further '...
        'to reach its runway. '...
        'The %.1f km runway offset adds %.0f%% to the effective route distance, so '...
        'ensure this overhead is acceptable for the intended operation.'], ...
        winner, dist_km, scores.estol_total, scores.evtol_total, margin, ...
        dom_label, abs(e_gap_pct), offset, offset, offset/dist_km*100);
end

end
